//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebQLCuaHangThucPham.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnhSP
    {
        public string MaAnh { get; set; }
        public string MaSP { get; set; }
        public string TenAnh { get; set; }
        public string URL { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
